name: Keep Render App Alive

on:
  schedule:
    - cron: "*/5 * * * *"  # runs every 5 minutes
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Curl keep-alive request
        run: curl -s https://francis-rombo.onrender.com > /dev/null

